services:
  backend:
    image: openjdk:21-jdk
    container_name: IntegrateBackend
    volumes:
      - ./Backend/INT221/target:/app
    working_dir: /app
    command: ["sh", "-c", "java -Dfile.encoding=UTF-8 -jar *.jar"]
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - LANG=th_TH.UTF-8
      - LANGUAGE=th_TH:th
      - LC_ALL=th_TH.UTF-8
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/int221?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Bangkok
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=sqleasy
    depends_on:
      database:
        condition: service_healthy
    networks:
      - My_Network

  database:
    image: mysql:latest
    container_name: IntegrateDatabase
    environment:
      MYSQL_ROOT_PASSWORD: sqleasy
      MYSQL_DATABASE: int221
      LANG: th_TH.UTF-8
      LC_ALL: th_TH.UTF-8
      TZ: UTC
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - My_Network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: nginx:latest
    container_name: IntegrateFrontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Frontend/SSI-3/dist:/usr/share/nginx/html
      - ./Frontend/SSI-3/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/mydomain:/etc/ssl/mydomain:ro
    depends_on:
      - backend
    networks:
      - My_Network

volumes:
  data:

networks:
  My_Network:

